### ISSUE TITLE
some songs play incorrectly

### ISSUE THREAD

**Issue by cyberic99** [mtimmerkamp/libsidplayfp-python#1]
Hello @mtimmerkamp , anf thank you for this project.

I tried the example with severa songs, and some of them seem to play incorrectly, or have their start cut, like for instance "Tintin on the Moon" by jeroen Tel, or "Monty on the run" by Rob Hubbard.

I know this is only an example, but what does it miss to play these songs correctly?

Thanks

**Comment by mtimmerkamp** [comment]
Hi @cyberic99,

I'm not entirely sure what's going wrong on your side. But I suspect you are not setting up the tunes correctly before loading them into the player (the example in the documentation also does it incorrectly and requires an update). Before `player.load(tune)`, you should select the subtune to play via `tune.select_song(0)`, which will load the start song. If you do not do that, Monty on the run will just be silent and Tintin on the Moon plays some random notes. Initializing the tune correctly fixes this on my side.

**Comment by cyberic99** [comment]
you're right!

I tested both songs after your fixes, and the tunes now play correctly. thanks!

**Comment by mtimmerkamp** [comment]
Documentation was updated by abf00c89ded0c650346ecffdb0af72bb03c3fe98
